apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle18xe
  namespace: application-ns
  labels:
    app: database
    version: 18.4.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 18.4.0.1
  template:
    metadata:
      name: oracle18xe
      labels:
        app: database
        version: 18.4.0.1
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: filler-app-db-creation
          configMap:
            name: filler-app-db-creation # Startup Scripts as configmaps
      containers:
        - name: oracle18xe
          image: pvargacl/oracle-xe-18.4.0:latest
          command:
            - /opt/oracle/runOracle.sh
          imagePullPolicy: Always
          resources:
            requests:
              memory: 6Gi
          ports:
            - name: listener
              containerPort: 1521
            - name: oemexpress
              containerPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: filler-app-db-creation
              mountPath: /opt/oracle/scripts/startup # Startup scripts directory
  serviceName: oracle18xe-db