apiVersion: v1
kind: Service
metadata:
  name: oracle18xe-svc
  namespace: application-ns
  labels:
    app: database
    version: 18.4.0.1
spec:
  selector:
    app: database
    version: 18.4.0.1
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
      name: listener
    - protocol: TCP
      port: 5500
      targetPort: 5500
      name: oemexpress
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oracle18xe
  namespace: application-ns
  labels:
    app: database
    version: 18.4.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 18.4.0.1
  template:
    metadata:
      name: oracle18xe
      labels:
        app: database
        version: 18.4.0.1
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: startup-scripts # Startup Scripts as configmaps
          projected:
            sources:
              - configMap:
                  name: log-miner-config
              - configMap:
                  name: filler-app-db-creation
      containers:
        - name: oracle18xe
          image: oracle/database:19.3.0-ee
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 4Gi
          ports:
            - name: listener
              containerPort: 1521
            - name: oemexpress
              containerPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            - name: startup-scripts
              mountPath: "/opt/oracle/scripts/startup"
          env:
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: oracle-admin-auth
                  key: password
                  optional: false
  serviceName: oracle18xe-db