apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle18xe
  namespace: oracle-namespace
  labels:
    app: database
    version: 18.4.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      version: 18.4.0.1
  template:
    metadata:
      name: oracle18xe
      labels:
        app: database
        version: 18.4.0.1
    spec:
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
      # add your volume mount for your persistent storage here
      containers:
        - name: oracle18xe
          image: pvargacl/oracle-xe-18.4.0:latest
          command:
            - /opt/oracle/runOracle.sh
          imagePullPolicy: Never
          resources:
            requests:
              memory: 6Gi
          ports:
            - name: listener
              containerPort: 1521
              hostPort: 1521
            - name: oemexpress
              containerPort: 5500
              hostPort: 5500
          volumeMounts:
            - name: dshm
              mountPath: "/dev/shm"
            # add your persistent storage for DB files here
          env:
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_PWD #Read the key call ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oradb #Read from a configmap called oradb
                  key: ORACLE_CHARACTERSET #Read the key call ORACLE_CHARACTERSET