kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ora-vol1
  namespace: oracle-namespace
  labels:
    app: oracle12c
spec:
  storageClassName: pure-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi