apiVersion: v1
kind: Service
metadata:
  name: filler-app-svc
  namespace: application-ns
  labels:
    app: filler-app
    version: "1.0.0"
spec:
  selector:
    app: filler-app
    version: "1.0.0"
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: traffic