apiVersion: v1
kind: Service
metadata:
  name: filler-app-svc
  namespace: debezium-example
  labels:
    app: filler-app
    version: "1.0.0"
spec:
  selector:
    app: filler-app
    version: "1.0.0"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: traffic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filler-app
  namespace: debezium-example
  labels:
    app: filler-app
    version: "1.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filler-app
      version: "1.0.0"
  template:
    metadata:
      name: filler-app
      labels:
        app: filler-app
        version: "1.0.0"
    spec:
      containers:
        - name: filler-app
          image: logistic-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: tomcat
              containerPort: 8080
          env:
            - name: POSTGRE_DB_HOST
              value: "$(POSTGRES_SVC_SERVICE_HOST)"

            - name: POSTGRE_DB_PORT
              value: "$(POSTGRES_SVC_SERVICE_PORT)"

            - name: POSTGRE_DB_NAME
              value: logisticapp

            - name: POSTGRE_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-db-auth
                  key: username

            - name: POSTGRE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-auth
                  key: password