apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgresql
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    plugin.name: pgoutput
    database.dbname: "logisticapp"
    database.hostname: postgres-svc
    database.port: 5432
    database.user: logisticapp
    database.password: vn53nag
    database.server.name: postgres
    table.include.list : "public.envio"
    database.history.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092