kind: Service
apiVersion: v1
metadata:
  name: kafka-connect
  namespace: application-ns
spec:
  type: NodePort
  selector:
    app: kafka-connect
  ports:
    - port: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: confluentinc/cp-kafka-connect
          ports:
            - containerPort: 8083
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: $(KAFKA_SERVICE_HOST):$(KAFKA_SERVICE_PORT)
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_GROUP_ID
              value: cdc_application
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: cdc-config
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: cdc-offset
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: cdc-status
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: localhost
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/java"



