apiVersion: v1
kind: Service
metadata:
  name: debezium-svc
  namespace: application-ns
  labels:
    app: debezium
spec:
  selector:
    app: debezium
  ports:
    - port: 8083
      targetPort: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium
  namespace: application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium
          image: debezium/connect:1.4
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: "$(KAFKA_SVC_SERVICE_HOST):$(KAFKA_SVC_SERVICE_PORT)"
            - name: GROUP_ID
              value: "1"
            - name: CONFIG_STORAGE_TOPIC
              value: connect_configs
            - name: OFFSET_STORAGE_TOPIC
              value: connect_offsets
            - name: KEY_CONVERTER
              value: io.confluent.connect.avro.AvroConverter
            - name: VALUE_CONVERTER
              value: io.confluent.connect.avro.AvroConverter
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              value: localhost
            - name: CONNECT_REST_PORT
              value: "8083"
            - name: CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_HOST):$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_PORT)"
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_HOST):$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_PORT)"
