kind: Service
apiVersion: v1
metadata:
  name: kafka-connect-svc
  namespace: cdc-demo
spec:
  selector:
    app: kafka-connect
  ports:
    - port: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: cdc-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: debezium
          image: debezium/connect
          ports:
            - containerPort: 8083
          env:
            - name: BOOTSTRAP_SERVERS
              value: "$(KAFKA_SVC_SERVICE_HOST):$(KAFKA_SVC_SERVICE_PORT)"
            - name: GROUP_ID
              value: "1"
            - name: REST_ADVERTISED_HOST_NAME
              value: localhost
            - name: REST_PORT
              value: "8083"
            - name: CONFIG_STORAGE_TOPIC
              value: connect_configs
            - name: OFFSET_STORAGE_TOPIC
              value: cdc-offset
            - name: STATUS_STORAGE_TOPIC
              value: cdc-status
            - name: KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: INTERNAL_KEY_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: INTERNAL_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: KEY_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_HOST):$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_PORT)"
            - name: VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_HOST):$(KAFKA_SCHEMA_REGISTRY_SVC_SERVICE_PORT)"
