apiVersion: v1
kind: Service
metadata:
  name: kafka-schema-registry-svc
  namespace: application-ns
  labels:
    app: kafka-schema-registry
spec:
  ports:
    - port: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-schema-registry
  namespace: application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      containers:
        - name: kafka-schema-registry
          image: confluentinc/cp-schema-registry:7.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "PLAINTEXT://$(KAFKA_SVC_SERVICE_HOST):$(KAFKA_SVC_SERVICE_PORT)"
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: localhost
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://localhost:8081"
            - name: SCHEMA_REGISTRY_DEBUG
              value: "true"