apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: application-ns
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: plaintext
    - port: 9999
      name: jmx
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: application-ns
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka-svc"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 9999
              name: jmx
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "$(ZOOKEEPER_SVC_SERVICE_HOST):$(ZOOKEEPER_SVC_SERVICE_PORT)"