kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: application-ns
spec:
  selector:
    app: kafka-manager
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: application-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
        - name: kafka-manager
          image: sheepkiller/kafka-manager
          ports:
            - containerPort: 9000
          env:
            - name: ZK_HOSTS
              value: "zookeeper-svc:2181"